RDKTV-3815: WPEFramework_crashes_in_std_terminate
rdkcentral/rdkservices pull request #1018
Opened 2021-03-31 15:32 UTC by acheri988

Reason for change:
device::Manager::Initialize exception handling is
enabled in HdcpProfile.cpp
Test Procedure: None
Risks: Low

Change-Id: Ib811da8b55cbe250c002a5d278f97231f13d999e
Signed-off-by:Anooj Cheriyan <Anooj_Cheriyan@comcast.com>

2021-03-31 15:54 UTC, anand-ky requested changes

2021-03-31 15:54 UTC, anand-ky commented on HdcpProfile/HdcpProfile.cpp
> +                LOGINFO("device::Manager::Initialize failed");
Pls change this to LOGERROR and add some details on the exception (e.what())

2021-03-31 15:54 UTC, anand-ky commented on HdcpProfile/HdcpProfile.cpp
> +                LOGINFO("device::Manager::Initialize failed");
Also we need to have some error handling and recovery from this error.

2021-04-28 14:00 UTC, vijs commented
Closing this outdated PR. Please submit this to the latest sprint branch if needed.

2021-04-28 14:00 UTC, closed without merging