RDKTV-3762: Reopen if db removed
rdkcentral/rdkservices pull request #1027
Opened 2021-04-05 15:14 UTC by npoltorapavlo

Reason for change: If db file is removed while
connection is open, read operations work,
write operations fail with SQLITE_READONLY.
If such errors occur, check whether db file exists
and reopen if needed.
Test Procedure: See ticket.
Risks: Low
Signed-off-by: Nikita Poltorapavlo <npoltorapavlo@productengine.com>

2021-04-07 21:39 UTC, anand-ky requested changes

2021-04-07 21:39 UTC, anand-ky commented on PersistentStore/PersistentStore.cpp
> +            SQLITE_LOCK
Can we avoid app level locks for the reads? This would restrict simultaneous reads from the PersistentStore.

2021-04-08 11:54 UTC, npoltorapavlo commented on PersistentStore/PersistentStore.cpp
> +                result = false; // Seems open!
yes. If connected and file exists, it's an invalid call

2021-04-12 16:16 UTC, anand-ky approved these changes

2021-04-12 16:16 UTC, merged