Sprint/2103
rdkcentral/rdkservices pull request #1198
Opened 2021-05-13 16:30 UTC by ddevad

2021-05-13 17:52 UTC, apatel859 approved these changes

2021-05-14 13:58 UTC, anand-ky requested changes

2021-05-14 13:58 UTC, anand-ky commented on DisplaySettings/DisplaySettings.cpp
> +	    Core::JSONRPC::Handler& DisplaySettings_v2 = JSONRPC::CreateHandler({ 2 }, *this);
We don't need to create this handler. You can just use the overloaded registerMethod() and pass the versions to be supported. Pls refer to System Plugin for example.

2021-05-14 17:59 UTC, closed without merging

2021-05-14 17:59 UTC, ddevad commented
will add new one