RDK-32486: Audio Mode Settings Override (Amlogic)
rdkcentral/rdkservices pull request #1716
Opened 2021-08-17 13:55 UTC by ahmedShafi12

Reason for change: Audio Mode Settings Override (Amlogic)
    Test Procedure: Curl Cmd
    Risks: Low

Signed-off-by: Shafi <shafi.ahmed@sky.uk>

2021-08-20 18:13 UTC, apatel859 approved these changes

2021-09-06 16:08 UTC, apatel859 submitted a review, later dismissed

2021-09-07 11:12 UTC, apatel859 submitted a review, later dismissed

2021-09-07 13:09 UTC, anand-ky requested changes

2021-09-07 13:09 UTC, anand-ky commented on DisplaySettings/DisplaySettings.cpp
> +            registerMethod("setMS12ProfileSetttingsOverride", &DisplaySettings::setMS12ProfileSetttingsOverride,this);
Please correct the spelling for Settings - setMS12ProfileSetttingsOverride

2021-09-07 15:00 UTC, anand-ky approved these changes

2021-09-07 17:36 UTC, merged