DELIA-53637: Check if interface and gateway IP are in the same network
rdkcentral/rdkservices pull request #2056
Opened 2021-12-13 17:22 UTC by arunvijas

Reason for change: added changes for For local testing
Test Procedure: Verifty TCH device
Risks: None
Signed-off-by: Arun Vijay asathy881@cable.comcast.com

2021-12-20 19:18 UTC, karuna2git requested changes

2021-12-20 19:18 UTC, karuna2git commented on Network/Network.cpp
> +                if (getRFCConfig("Device.DeviceInfo.X_RDKCENTRAL-COM_RFC.Feature.Network.ManualIPSettings.Enable", param))
Change it like,

if (Utils::getRFCConfig("Device.DeviceInfo.X_RDKCENTRAL-COM_RFC.Feature.Network.ManualIPSettings.Enable", param))

2021-12-22 19:15 UTC, karuna2git approved these changes

2022-01-03 12:56 UTC, anand-ky approved these changes

2022-01-03 12:57 UTC, merged