[WebKitBrowser] Improve GLib-API support
rdkcentral/rdkservices pull request #2075
Opened 2022-01-03 15:35 UTC by emutavchi

Based on work done by Haseena:
https://github.com/HaseenaSainul/rdkservices/tree/development/webkit-iface-syncup

2022-01-03 15:54 UTC, emutavchi commented
@HaseenaSainul @MFransen69 could you please review?

2022-01-05 05:02 UTC, HaseenaSainul requested changes
In general, code changes seems fine for me. 
But I am not happy with Injected bundle glib version keeping outside InjectedBundle folder extension. So I would like to have both webkit version changes under injected bundle itself. there you can create subfolders for both versions with appropriate naming

2022-01-05 14:14 UTC, emutavchi commented on WebKitBrowser/WebKitImplementation.cpp
Hi @HaseenaSainul, thanks for looking into this.

> So I would like to have both webkit version changes under injected bundle itself. there you can create subfolders for both versions with appropriate naming

not sure what you mean. Injected bundle is part of WebKit (with GLib-API enabled). So, it makes sense to me to move Extension sources out of plugin InjectedBundle.

> Why you have skipped the g_signal_connect for notify::is-web-process-responsive ?

Webkit Glib API triggers it after the web process crash, which was a bit confusing. So, I removed it at some point and probably forgot about it. I can bring it back.

2022-01-05 14:29 UTC, emutavchi commented on WebKitBrowser/WebKitImplementation.cpp
@HaseenaSainul  I've brought back handling of notify::is-web-process-responsive, could you please review?

2022-01-11 13:17 UTC, MFransen69 requested changes

2022-01-11 14:05 UTC, emutavchi commented on WebKitBrowser/CMakeLists.txt
> +    add_subdirectory(Extension)
Hi @MFransen69, thanks for review.

My understanding is that GLib API doesn't allow user-provided injected bundles, and that was the reason for switching to extension API. there are other things that are currently not supported with extension API and need to be added later.

I did address your concern with the configuration.

2022-01-11 14:38 UTC, HaseenaSainul commented on WebKitBrowser/CMakeLists.txt
> +    add_subdirectory(Extension)
Then where will be used libWPEExtension.so ? In metro build we are loading GLIB version of injected bundle with wpe-2.28 version and it is working.

2022-01-11 15:26 UTC, MFransen69 approved these changes

2022-01-11 15:31 UTC, HaseenaSainul approved these changes

2022-01-11 16:41 UTC, goruklu approved these changes

2022-01-11 16:41 UTC, merged