METROL-103: Updates Packager
rdkcentral/rdkservices pull request #224
Opened 2020-09-02 16:53 UTC by MFransen69

Syncs Packager with the latest updates from ThunderNanoServices

2020-09-02 18:09 UTC, pwielders requested changes
This is was changed delibratly to allow for Comcast to use their own provisioning and t not break the metrological way of working. So I think you can drop this pull-request

2020-09-02 18:10 UTC, pwielders commented
But we do need the EXTERNAL.... so the CMakefiles.txt changes should not be pushed, the EXTERNAL should

2020-09-03 08:01 UTC, MFransen69 commented
> But we do need the EXTERNAL.... so the CMakefiles.txt changes should not be pushed, the EXTERNAL should

Done

2020-09-03 17:21 UTC, pwielders approved these changes

2020-09-03 18:32 UTC, merged