RDK-34330-Add Mfr to Device Info API for Element
rdkcentral/rdkservices pull request #2288
Opened 2022-03-07 12:20 UTC by MManja792

Reason for change: Friendly_id will return from Mfr lib
Test Procedure: Get frindly_id
Risks: None
Signed-off-by: Mallikarjun_manjari@comcast.com

2022-03-07 12:40 UTC, anand-ky requested changes

2022-03-07 12:40 UTC, anand-ky commented on SystemServices/SystemServices.cpp
> +	uint32_t  SystemServices::getModelName()
Pls reuse getManufacturerData() which already implements this logic.

2022-03-08 19:00 UTC, MManja792 commented on SystemServices/SystemServices.cpp
> +            if (!parameter.compare(MODEL_NAME) || !parameter.compare(FRIENDLY_ID)) {
Not required, removed.

2022-03-08 19:04 UTC, anand-ky approved these changes

2022-03-08 19:04 UTC, merged