RDK-35853: Crash observed when few plugins are activated
rdkcentral/rdkservices pull request #2349
Opened 2022-03-16 10:44 UTC by kathiravancomcast

From: kchinn681 kathiravan_chinnadurai@comcast.com

Subject: Crash observed when few plugins are activated from Controller UI in CMF-RPi
Reason for change:Crash observed when few plugins are activated from Controller UI in CMF-RPi
Test Procedure: activate html app using controller.ui
Risks: Low
Signed-off-by: kathiravan chinnadurai kathiravan_chinnadurai@comcast.com
Source: COMCAST
License: GPLV2
Upstream-Status: Pending

2022-03-16 18:44 UTC, mfiess requested changes
Let's discuss, I think we'll want a more dynamic approach for when clientidentifier is not specified.

2022-03-17 10:21 UTC, swati-varahagiri approved these changes

2022-04-05 12:52 UTC, mfiess approved these changes

2022-04-07 14:53 UTC, merged

2022-04-12 12:38 UTC, pradeeptakdas commented
Internal JIRA for tracking https://ccp.sys.comcast.net/browse/RDKCOM-2979