RDK-34041- Passing unchecked strings to system command
rdkcentral/rdkservices pull request #2359
Opened 2022-03-17 10:36 UTC by MonekaLakshmi

Reason for change: Remove RunScript() and execute the script directly using v_secure_system()

2022-03-17 10:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/rdkservices?pullRequest=2359) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/rdkservices?pullRequest=2359) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/rdkservices?pullRequest=2359) it.</sub>

2022-03-17 11:16 UTC, anand-ky requested changes
We need to upstream secure_wrapper before including this change on rdkcentral.

2022-04-19 11:03 UTC, Firdose2109 commented
Can one of the admins verify this patch?

2022-04-22 14:43 UTC, anand-ky commented
Closing this patch. Pls resubmit when we can open source v_secure_system().

2022-04-22 14:43 UTC, closed without merging