RDKTV-14660: Remove ARC/eARC HPD signal dependency for audio routing
rdkcentral/rdkservices pull request #2427
Opened 2022-04-04 17:33 UTC by ddevad

Reason for change:1) Added support for Audio Device Power
status API in Hdmicecsink & Displaysettings
2) Audio Device power status should be checked by TV once
any audio device connection is detected
3) Audio Routing to rely completely on ARC Initiation &
System audio mode events
4) Remove HPD ON handling from dsHdmiEventHandler and retain
HPD OFF handling
5) Initiate cec device ping immediately on HDMI ARC/eARC
Hotplug
Test Procedure: Refer Ticket
Risks: Medium

Signed-off-by: Deekshit Devadas deekshit.devadasy@sky.uk

2022-04-04 19:53 UTC, anand-ky commented
@ddevad - Pls also update documentation in the json files.

2022-04-05 13:42 UTC, apatel859 commented on HdmiCecSink/HdmiCecSink.cpp
> +#define HDMICECSINK_METHOD_REQUEST_AUDIO_DEVICE_POWER_STATUS   "requestAudioDevicePowerStatus"
why not get?

2022-04-05 13:45 UTC, apatel859 commented on HdmiCecSink/HdmiCecSink.cpp
> +           if((header.from.toInt() == LogicalAddress::AUDIO_SYSTEM) && (HdmiCecSink::_instance->m_audioDevicePowerStatusRequested)) {
why you limiting power status to audio device specific only ...that check can be done on the caller side if you are not interested on other devices power status

2022-04-05 13:48 UTC, apatel859 commented on HdmiCecSink/HdmiCecSink.cpp
> +                        _instance->smConnection->sendTo(LogicalAddress::AUDIO_SYSTEM, MessageEncoder().encode(GiveDevicePowerStatus()), 500);
pass AUDIO_SYSTEN as a argument to request API

2022-04-05 15:04 UTC, apatel859 approved these changes

2022-04-05 15:05 UTC, apatel859 requested changes
remove docs update

2022-04-05 17:19 UTC, anand-ky approved these changes

2022-04-05 17:19 UTC, merged