RDK-36282: Add support for passing user scripts
rdkcentral/rdkservices pull request #2468
Opened 2022-04-15 13:06 UTC by Scony

allows injecting user scripts via config:
```
"userscripts": ["/tmp/data/script.js", "script2.js", "nonexistent"]
```

2022-04-15 13:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/rdkservices?pullRequest=2468) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/rdkservices?pullRequest=2468) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/rdkservices?pullRequest=2468) it.</sub>

2022-04-15 15:16 UTC, emutavchi approved these changes
looks good to me. let's wait for a review from Metrological team.

2022-04-19 09:19 UTC, MFransen69 requested changes

2022-04-19 09:19 UTC, MFransen69 commented on WebKitBrowser/WebKitImplementation.cpp
> +                    SYSLOG(Trace::Information, (_T("Loading user script '%s'"), scriptPath.Value().c_str()));
Hi, for the error message above it is consistent with other error message in this file to use SYSLOG however for this line  where it is informational I would propose to use "TRACE(Trace::Information, ..." here so we do not pollute the syslog output with informational messages

2022-04-19 09:19 UTC, MFransen69 commented on WebKitBrowser/WebKitImplementation.cpp
> +                        auto success = g_file_get_contents(path.c_str(), &scriptContent, nullptr, nullptr);
I guess you do not always expect these scripts to be in the datapath? As that should be the case for a stack where datapath is filled could we (like for the extension path) make these relative to the datapath when datapath is set (or additionally check if the scriptpath is a relative path, does not start with a /, and only then append it the the datapath)?

2022-04-19 09:19 UTC, MFransen69 commented on WebKitBrowser/WebKitImplementation.cpp
> +                        auto success = g_file_get_contents(path.c_str(), &scriptContent, nullptr, nullptr);
I guess you do not always expect these scripts to be in the datapath? As that should be the case for a stack where datapath is filled could we (like for the extension path) make these relative to the datapath when datapath is set (or additionally check if the scriptpath is a relative path, does not start with a /, and only then append it the the datapath)?

2022-04-19 09:19 UTC, MFransen69 commented on WebKitBrowser/WebKitImplementation.cpp
> +            if (_config.UserScripts.IsSet()) {
As the code is similar to the above put it in a private function and call it in both places perhaps?

2022-04-19 09:19 UTC, MFransen69 commented on WebKitBrowser/WebKitImplementation.cpp
> +            if (_config.UserScripts.IsSet()) {
As the code is similar to the above put it in a private function and call it in both places perhaps?

2022-04-19 11:03 UTC, Firdose2109 commented
Can one of the admins verify this patch?

2022-04-20 11:55 UTC, Scony commented
@MFransen69 could you please re-review?

2022-04-20 13:47 UTC, merged