Modified DeviceIdentification plugin to fetch & build brcm specific code from external repository
rdkcentral/rdkservices pull request #251
Opened 2020-09-11 07:30 UTC by neeraj-deshpande

2020-09-22 11:55 UTC, MFransen69 submitted a review, later dismissed

2020-09-24 15:36 UTC, MFransen69 requested changes
Hi Neeraj, think I was not clear in my last request, sorry. It is not a special flag to override when to take the sources from Gerrit, the idea was that you could specify for a component to not take the sources from Gerrit (or RDK Central) but you could specify a folder to get the sources from (so you can have them local on a disk or something similar instead)

2020-09-28 06:55 UTC, MFransen69 submitted a review, later dismissed

2020-09-28 07:16 UTC, woutermeek approved these changes

2020-09-28 15:31 UTC, gladish approved these changes

2020-10-05 07:17 UTC, closed without merging