RDKTV-16030  Addressed class hierarchy review comments
rdkcentral/rdkservices pull request #2567
Opened 2022-05-05 16:31 UTC by tamilselvanak

2022-05-06 13:30 UTC, apatel859 requested changes
Could you setup a meeting including Anand K, Ramkumar, Deeksheet and me to finalize on this

2022-05-11 16:11 UTC, tamilselvanak commented
Hi @mhughesacn,
Sure will append those lines in top level NOTICE.

2022-05-16 16:15 UTC, apatel859 commented on ControlSettings/ControlSettingsTV.h
> +        uint32_t Release() const;
check on this if required

2022-05-16 16:26 UTC, apatel859 commented on ControlSettings/ControlSettings.cpp
> -	{
Are we doing unregister?

2022-05-16 16:30 UTC, apatel859 commented on ControlSettings/ControlSettingsSTB.json
> + "locator":"libControlSettingsSTB.so",
check if remove STB

2022-05-19 13:34 UTC, apatel859 commented on ControlSettings/ControlSettingsSTB.cpp
> +    std::string ControlSettingsSTB::getErrorString (tvError_t eReturn)
tv should be not be there in stb

2022-05-30 15:03 UTC, ddevad approved these changes

2022-06-08 10:31 UTC, apatel859 approved these changes

2022-06-08 10:31 UTC, merged