RDK-36267: Improve Efficiency of Network RDKServices APIs
rdkcentral/rdkservices pull request #2568
Opened 2022-05-06 05:22 UTC by ksanth850

Reason for change: Improves overall performance of clients apps using RDKServices and reduce number of IARM_Bus_Call
Test Procedure: Fetch interface and getipsettings value from netsrvmgr when first call or whenever onInterfaceIPchange event occurs otherwise use cache value for response.
Risks: High
Signed-off-by: Kumar Santhanam Kumar_Santhanam@comcast.com

2022-05-10 03:05 UTC, karuna2git requested changes

2022-05-10 03:05 UTC, karuna2git commented on Network/Network.cpp
>              if (ipv4Addr != "")
can you use !string::empty() function?

2022-05-10 03:05 UTC, karuna2git commented on Network/Network.cpp
>              if (ipv6Addr != "")
can you use string::empty()

2022-05-11 17:22 UTC, ksanth850 commented on Network/Network.cpp
>              if (ipv6Addr != "")
Done

2022-05-11 17:23 UTC, ksanth850 commented on Network/Network.cpp
>              if (ipv4Addr != "")
Modified it.

2022-05-11 17:23 UTC, ksanth850 commented on Network/Network.cpp
> +                if (!strcasecmp(onInterface.c_str(), "wifi"))
Modified it

2022-05-11 17:23 UTC, ksanth850 commented on Network/Network.cpp
> +                if (!strcasecmp(onInterface.c_str(), "wifi"))
Modified it

2022-05-11 17:28 UTC, ksanth850 commented on Network/Network.cpp
> +                            m_defInterfaceCache = internalResponse["interface"].String();
For second iteration should go with proper interface value.

2022-05-11 19:25 UTC, karuna2git approved these changes

2022-05-11 19:25 UTC, merged