RDKDEV-310: Monitor: Add changes for monitoring additional plugins
rdkcentral/rdkservices pull request #2666
Opened 2022-05-27 08:21 UTC by susanmary007

This commit brings in the changes to monitor the plugins configured
in 'PLUGIN_MONITOR_INSTANCES_LIST'.
'PLUGIN_MONITOR_INSTANCES_LIST' contains a semi-colon (';') separated
list of Monitor observable instances.
Each instance, in turn, is a comma (',') separated list defining an observable
instance elements ("callsign,memory,memorylimit,operational,window,limit").

2022-05-31 09:21 UTC, rjpdasilva commented
Hello, any update on this?

2022-06-07 15:23 UTC, pradeeptakdas commented
Internal JIRA for tracking https://ccp.sys.comcast.net/browse/RDKCOM-3133

2022-06-08 10:23 UTC, bramoosterhuis requested changes

2022-06-08 10:23 UTC, bramoosterhuis commented on Monitor/Monitor.config
> +        map()
I think the ``` map()``` should move after the ```list(GET instance_conf 5 limit)```. This keeps all the JSON stuff tighter together.

2022-06-08 14:17 UTC, susanmary007 commented
Created v2(https://github.com/rdkcentral/rdkservices/pull/2731)

2022-06-08 14:17 UTC, closed without merging