Sprint/2206 1
rdkcentral/rdkservices pull request #2717
Opened 2022-06-07 14:48 UTC by MManja792

RDK-36589: RDK System Thunder Service Support for Regionalization

Pushing code to 2206 sprint

2022-06-07 15:02 UTC, anand-ky requested changes

2022-06-07 16:45 UTC, MManja792 commented on SystemServices/System.json
> +	    "summary": "Sets the territory and region",
Updated

2022-06-07 16:45 UTC, MManja792 commented on SystemServices/SystemServices.cpp
> +		GetHandler(2)->Notify(EVT_ONTERRITORYCHNAGED, params);
Updated

2022-06-08 18:05 UTC, anand-ky commented
Temporary issue with CLA. force merging to meet deadline.

2022-06-08 18:05 UTC, merged