RDKTV-17804 : Element - Seeing black screen for 10-15 seconds
rdkcentral/rdkservices pull request #2952
Opened 2022-07-28 09:58 UTC by zhilarasi

Reason for change : Element - Seeing black screen for 10-15 seconds on launching YT/Peacock after wake up from DeepSleep

Test Procedure: TBD

Risks: None

2022-07-28 10:17 UTC, madanagopalt commented on RDKShell/RDKShell.cpp
> +bool availablePluginsPopulated = false;
change this variable name to gAvailablePluginsPopulated

2022-07-28 10:17 UTC, madanagopalt requested changes
please address given comments

2022-07-28 10:58 UTC, madanagopalt commented
looks good

2022-08-01 12:00 UTC, anand-ky approved these changes

2022-08-01 12:00 UTC, merged