Test rdk 37645 rev7
rdkcentral/rdkservices pull request #3073
Opened 2022-08-19 14:22 UTC by dwolaver

Verification build can be found at https://jenkins.ccp.xcal.tv/jenkins/job/Gerrit-Trigger-Custom-Verification-TopicName-Pipeline/75882/

2022-08-19 15:56 UTC, anand-ky requested changes

2022-08-19 15:56 UTC, anand-ky commented on VoiceControl/CHANGELOG.md
> +## [2.0.0] - 2022-08-18
As discussed, this includes a breaking change. Pls first make a minor version update to deprecate the voiceSessionByText API to ensure existing clients are not affected. Details about deprecation at under https://github.com/rdkcentral/rdkservices#versioning.

2022-08-19 15:56 UTC, anand-ky commented on VoiceControl/VoiceControl.cpp
> +            Register("voiceSessionTypes",     &VoiceControl::voiceSessionTypes,     this);
Pls update the VoiceControl.json schema to reflect the deprecated API and also add the new APIs and regenerate VoiceControlPlugin.md.

2022-08-22 10:17 UTC, npoltorapavlo commented
APIs should follow the JSON-RPC spec https://www.jsonrpc.org/specification#response_object
Please use error codes instead of the XRE Service Manager legacy param "success"

2022-09-09 21:13 UTC, closed without merging