RDK-36108: Set JSPP environment variables
rdkcentral/rdkservices pull request #3080
Opened 2022-08-22 09:14 UTC by Scony

This PR is a followup of https://github.com/rdkcentral/rdkservices/pull/3050 which implements and uses a mechanism for exporting extra environment variables from webkitbrowser plugin.

2022-08-22 13:15 UTC, emutavchi submitted a review, later dismissed

2022-08-29 14:16 UTC, MFransen69 requested changes

2022-08-29 14:16 UTC, MFransen69 commented on WebKitBrowser/WebKitImplementation.cpp
> +            Core::JSON::ArrayType<JsonObject> EnvVars;
Let's please use a strong type here and not JsonObject. That is easier to understand and type safe (and more efficient)

2022-08-31 16:00 UTC, MFransen69 approved these changes

2022-08-31 16:13 UTC, merged