DELIA-58272 : Log error code in webkitbrowser plugin when URL fails t…
rdkcentral/rdkservices pull request #3282
Opened 2022-10-07 12:41 UTC by simi-mathew

…o load

Reason for change: Log error code in webkitbrowser plugin when URL fails to load Test Procedure: Specified in ticket
Risks: NA

Signed-off-by: Simi Mathew <simim@tataelxsi.co.in>

2022-10-07 13:01 UTC, emutavchi approved these changes

2022-10-07 13:03 UTC, emutavchi requested changes

2022-10-07 13:03 UTC, emutavchi commented on WebKitBrowser/WebKitImplementation.cpp
> +            string message(string("{ \"url\": \"") + failingURI + string("\", \"Error message\": \"") + error->message + string("\", \"loadEvent\":") + Core::NumberType<uint32_t>(loadEvent).Text() +
I think it would be good to match WK, and suppress loadFailed notification of 'canceled' requests (and loadfinished as well)

2022-10-10 11:52 UTC, emutavchi approved these changes

2022-10-10 11:52 UTC, emutavchi commented
@modeveci  could you please review this as well?

2022-10-10 12:10 UTC, modeveci approved these changes
LGTM

2022-10-10 13:20 UTC, merged