RDK-34568: Expand AVInput RDK Service to include HDMI&CompositeInput …
rdkcentral/rdkservices pull request #3286
Opened 2022-10-10 10:37 UTC by dhivya-ilangovan

…APIs

Reason for change: Combine HdmiInput and CompositeInput Plugins into AVInput
Test Procedure: sanity testases on HDMI and COMPOSITE inputs
Risks: Low
Signed-off-by: Dhivya Ilangovan <dhivya.dilangovan@sky.uk>

2022-10-10 16:06 UTC, anand-ky requested changes

2022-10-10 16:06 UTC, anand-ky commented on AVInput/CHANGELOG.md
> +- Combine HdmiInput and CompositeInput Plugins into AVInput
This should be a minor version update since it's adding new functionality. Hope there is no breaking change.

2022-10-10 16:06 UTC, anand-ky commented on AVInput/AVInput.cpp
>  #define API_VERSION_NUMBER_MINOR 0
Need to also update this macro to match the version update in CHANGELOG.md

2022-10-11 11:07 UTC, dhivya-ilangovan commented
Created new PR to avoid multiple commit messages
https://github.com/rdkcentral/rdkservices/pull/3294

2022-10-11 11:07 UTC, closed without merging