RDK-39119: Implement LED control
rdkcentral/rdkservices pull request #3539
Opened 2022-12-16 21:01 UTC by acheri988

Reason for change:
Implement LED control
Test Procedure: None
Risks: Low

Change-Id: If3e38f36b3f9ca5713bb6fd52db9eb140ab32c36 Signed-off-by:Anooj Cheriyan <Anooj_Cheriyan@comcast.com>

2022-12-16 23:50 UTC, anand-ky requested changes

2022-12-16 23:50 UTC, anand-ky commented on LEDControl/CHANGELOG.md
> +### Change
Pls remove the ##Change label and comments below it. This was added for previous plugins that were present before we added the CHANGELOG. 
Also pls add the generic instructions at the top of the CHANGELOG similar to others - https://github.com/rdkcentral/rdkservices/blob/sprint/22Q4/Bluetooth/CHANGELOG.md

2022-12-16 23:50 UTC, anand-ky commented on LEDControl/LEDControl.cpp
> +                success = false;
Can we handle returning error object here. Pls take the time and handle all error scenarios for all the new APIs.

2022-12-19 20:37 UTC, acheri988 commented
New patch created: https://github.com/rdkcentral/rdkservices/pull/3548

2022-12-19 20:37 UTC, closed without merging