RDKTV-20779 - move factory mode evaluation before requests processing
rdkcentral/rdkservices pull request #3579
Opened 2022-12-27 05:03 UTC by madanwork

2023-01-03 16:44 UTC, binuinbaraj reviewed
Changes look good.

2023-01-03 17:07 UTC, anand-ky commented
@madanwork - Pls update version in the macro also in RDKShell.cpp https://github.com/rdkcentral/rdkservices/blob/e2fc6b63e83c1a4b18f01fa9bbcfcfd0609b4b52/RDKShell/RDKShell.cpp#L54.
This will ensure that calling Controller.Status on this plugin will return the updated version (1.3.10)

2023-01-03 17:08 UTC, anand-ky requested changes
Pls update patch version in macro

2023-01-04 12:04 UTC, anand-ky approved these changes

2023-01-04 12:05 UTC, merged