RDK-37916: Unit tests for OCIContainer
rdkcentral/rdkservices pull request #3891
Opened 2023-03-25 19:22 UTC by melhar098

2023-03-26 18:22 UTC, goruklu requested changes

2023-03-26 18:22 UTC, goruklu commented on OCIContainer/CHANGELOG.md
> +- Added unit tests for OCIContainer
you need to update the revision (1.0.0->1.0.1) number in https://github.com/rdkcentral/rdkservices/blob/main/OCIContainer/OCIContainer.cpp#L10 and have a separate entry for 1.0.1 in CHANGELOG.md file

2023-03-27 14:31 UTC, goruklu requested changes
can you move the new revision to the top ?

2023-03-27 14:53 UTC, goruklu submitted a review, later dismissed

2023-03-27 16:21 UTC, anand-ky approved these changes

2023-03-27 16:21 UTC, merged