RDK-40655 Local Speech Synthesis (Offline TTS) for Flex 2.0 - Nuance
rdkcentral/rdkservices pull request #4080
Opened 2023-05-30 11:24 UTC by cmurug728

Reason for change: Feature development
Test Procedure: TBD
Priority: P1
Risks: None
Signed-off-by: vishnu dinakaran <Vishnu_Dinakaran@comcast.com> chockalingam murugan <chockalingam_murugan@comcast.com>

2023-06-01 08:22 UTC, varumugam123 requested changes

2023-06-05 09:10 UTC, cmurug728 commented on TextToSpeech/impl/TTSManager.cpp
> +         auto it = m_defaultConfiguration.m_others_local.find(key);
@varumugam123 There is language like en-US in both online and local , So I'm planning to append local for local voices in m_others
Eg:
voice_for_en-US - carol
voice_for_local_en-US -ava

2023-06-05 09:15 UTC, cmurug728 commented on TextToSpeech/impl/TTSManager.cpp
> +         auto it = m_defaultConfiguration.m_others_local.find(key);
So the function listVoices only return voices for secureEndpoint and listLocalVoices return voices for localendPoint ,is it fine?

2023-06-06 07:00 UTC, cmurug728 commented on TextToSpeech/impl/TTSManager.cpp
> +    if( m_defaultConfiguration.hasValidLocalEndpoint() && endpoint_updated ) {
There is a case where default secureendpoint is set as local just like in Hisense/platco in that case localendpoint is set to ""

2023-08-08 18:50 UTC, closed without merging