Dev ut 23 q3
rdkcentral/rdkservices pull request #4196
Opened 2023-07-07 03:23 UTC by viveksinghnarwaria

2023-07-07 03:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/rdkservices?pullRequest=4196) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/rdkservices?pullRequest=4196) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/rdkservices?pullRequest=4196) it.</sub>

2023-07-07 03:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/rdkservices?pullRequest=4196) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/rdkservices?pullRequest=4196) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/rdkservices?pullRequest=4196) it.</sub>

2023-07-09 10:55 UTC, anand-ky requested changes
Pls check review comments.
Also sign the CLA (Customer License Agreement). You should see the msg "CLA not Signed yet" on this PR.

2023-07-09 10:55 UTC, anand-ky commented on MaintenanceManager/MaintenanceManager.cpp
> +#ifdef DISABLE_THUNDER_CLIENT_IN_MAINTENANCE_MANAGER_GTEST
We should not make any changes to source code to support unit testing. If you want a null ptr, pls add a mock in unit test code. You can refer to other unit tests for reference.

2023-07-09 10:55 UTC, anand-ky commented on MaintenanceManager/MaintenanceManager.cpp
> +#ifdef DISABLE_THUNDER_CLIENT_IN_MAINTENANCE_MANAGER_GTEST
We should not make any changes to source code to support unit testing. If you want a null ptr, pls add a mock in unit test code. You can refer to other unit tests for reference.

2023-07-09 10:55 UTC, anand-ky commented on Tests/mocks/thunder/ServiceMock.h
> +	//MOCK_METHOD(void*, Root, (const uint32_t, const uint32_t, const string&), (override));
Pls remove this change if not required instead of commenting it

2023-07-09 10:55 UTC, anand-ky commented on Tests/tests/test_Packager.cpp
> +/*
I see some of the code is commented. Are we planning to support it later? If not pls remove.

2023-07-17 11:54 UTC, closed without merging

2023-07-17 12:31 UTC, viveksinghnarwaria commented
re