RDK-32249: RemoteControl plugin refactor
rdkcentral/rdkservices pull request #4279
Opened 2023-08-02 20:26 UTC by klu339

Reason for change: Modify RCP to be a json pass thru and remove unit tests
Test Procedure: Full RCP regression test
Risks: Low

2023-08-04 15:41 UTC, egalla204 requested changes

2023-08-04 15:41 UTC, egalla204 commented on Tests/mocks/Iarm.h
did you add these IRMgr things?  If not, we should just leave them in there

2023-08-08 14:06 UTC, klu339 commented on RemoteControl/RemoteControl.cpp
>  #include "irMgr.h"
No - I'll remove it!

2023-08-08 14:06 UTC, klu339 commented on RemoteControl/RemoteControl.cpp
> -#define IARM_IRDB_CALLS_TIMEOUT     (10 * 1000)  // 10 seconds, in milliseconds
Can do - forgot to copy over the ipc timeout versions of iarm calls

2023-08-11 20:19 UTC, egalla204 approved these changes

2023-09-01 14:34 UTC, anand-ky approved these changes

2023-09-01 14:34 UTC, merged