RDK-42925 : RDKShell changes for Factory HAL Gerrit migration
rdkcentral/rdkservices pull request #4356
Opened 2023-08-25 05:10 UTC by gopikamottemmalvalsan

2023-08-25 05:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/rdkservices?pullRequest=4356) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/rdkservices?pullRequest=4356) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/rdkservices?pullRequest=4356) it.</sub>

2023-09-21 11:26 UTC, apatel859 approved these changes

2023-09-21 11:28 UTC, apatel859 requested changes
could you update the CHANGE log file

2024-05-22 17:11 UTC, anand-ky commented
Closing older PRs. Pls bring it to latest sprint/main branches if required.

2024-05-22 17:11 UTC, closed without merging