RDK-43314:Hdmi EDID Allm support
rdkcentral/rdkservices pull request #4389
Opened 2023-09-05 06:39 UTC by aishwariya15

Reason for change:Added the Wpeframework and the devicesettings Changes Test Procedure: NA
Risks: None
Signed-off-by: Aishwariya B aishwariya.bhaskar@sky.uk

2023-09-15 12:15 UTC, apatel859 requested changes
Update json documentgation. Also we need to check why API named as Edid2Allm

2023-09-19 13:09 UTC, apatel859 commented on AVInput/AVInput.json
> +                        "summary": "The allm bit value in edid",
could you use ALLM consistently

2023-09-19 13:11 UTC, apatel859 requested changes

2023-09-19 18:02 UTC, apatel859 commented on AVInput/AVInput.json
> +            "summary": "Returns the EDID Allm bit value.",
ALLM

2023-09-19 18:02 UTC, apatel859 commented on AVInput/AVInput.cpp
> +#define AVINPUT_METHOD_SET_EDID_ALLM_SUPPORT "setEdid2AllmSupport"
where is the gunit test coverage for this two new method

2023-09-20 06:57 UTC, aishwariya15 commented on Tests/mocks/devicesettings/HdmiInputMock.h
> +    MOCK_METHOD(void, setEdid2AllmSupport, (int iHdmiPort, bool allmSupport), (const, override));
Hi, 
There is no mock header directly available for AVInputMock.h, Should we need to create it?

2023-09-20 13:50 UTC, apatel859 approved these changes

2023-09-20 14:23 UTC, merged