RDKShell: Skip SetFocus to false for Hibernated plugins
rdkcentral/rdkservices pull request #4614
Opened 2023-11-03 09:10 UTC by adrianM27

2023-11-03 10:56 UTC, adrianM27 commented on RDKShell/RDKShell.cpp
> +                                if (service.JSONState == PluginHost::MetaData::Service::state::HIBERNATED)
worth to consider excluding SUSPENDED state, only If we confirm the call to Focused(false) is not needed for hibernated or suspended apps

2023-11-03 19:25 UTC, goruklu commented
this looks good to me but @binuinbaraj should review as well.

2023-11-17 00:36 UTC, goruklu requested changes

2023-11-17 00:36 UTC, goruklu commented on RDKShell/RDKShell.cpp
> +                //Reset app suspended/hibernated for launch
Might be good to use the #ifdef HIBERNATE_SUPPORT_ENABLED everywhere we use suspendOrHibernateApps array and mutex.

2023-11-17 00:36 UTC, goruklu commented on RDKShell/RDKShell.cpp
> +std::mutex suspendedOrHibernatedAppsMutex;
Might be good to use the #ifdef HIBERNATE_SUPPORT_ENABLED everywhere we use suspendOrHibernateApps array and mutex.

2023-11-17 00:36 UTC, goruklu commented on RDKShell/RDKShell.cpp
> +            suspendedOrHibernatedAppsMutex.lock();
Might be good to use the #ifdef HIBERNATE_SUPPORT_ENABLED everywhere we use suspendOrHibernateApps array and mutex.

2023-11-17 14:35 UTC, binuinbaraj reviewed
Changes looks good.

2023-11-17 15:18 UTC, goruklu approved these changes

2023-11-17 15:38 UTC, merged