RDK-29274:Thunder APIs for AutoReboot
rdkcentral/rdkservices pull request #473
Opened 2020-11-16 17:49 UTC by livinsunny519

Reason for change: Added new method for
fwPendingReboot & fwDelayReboot.
'{"jsonrpc":"2.0","id":"3","method":"org.rdk.System.2.fwPendingReboot","params":{}}' 
'{"jsonrpc":"2.0","id":"3","method":"org.rdk.System.2.fwDelayReboot","params":{"fwDelayReboot":int seconds}}'
Test Procedure: Refer to Jira Ticket.

2020-11-16 17:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/rdkservices?pullRequest=473) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/rdkservices?pullRequest=473) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/rdkservices?pullRequest=473) it.</sub>

2020-11-26 16:59 UTC, livinsunny519 commented
@bobseamon @vijs could you please review

2020-12-01 14:36 UTC, bobseamon requested changes
These changes add new methods to the system service.  As such, the system service should be incremented to version 2.  Once that change is made, documentation needs to be updated at https://wiki.rdkcentral.com/pages/viewpage.action?pageId=105516014 .  If you don't have access, I can make the doc changes, but they will need to be documented before the change is merged.

2020-12-07 18:00 UTC, livinsunny519 commented
updated and rebased the code @bobseamon

2020-12-08 07:03 UTC, closed without merging

2020-12-11 11:08 UTC, livinsunny519 commented
addressed in https://github.com/rdkcentral/rdkservices/pull/552.