RDKVREFPLT-721: [BCM72126] RDK Services: DeviceIdentification plugin is not enabled in the device
rdkcentral/rdkservices pull request #4894
Opened 2024-02-07 11:23 UTC by RajapriyaRadhakrishnan

Reason for change: Enabled the DeviceIdentification plugin and added methods for retrieving Serial number, Chip Id and Firmware version.

Test Procedure:

root@brcm972126ott-refboard-PR0013720:~#  curl -X POST http://127.0.0.1:9998/jsonrpc -d '{"jsonrpc":"2.0","id":"42","method":"DeviceIdentification.1.deviceidentification"}';echo; {"jsonrpc":"2.0","id":42,"result":{"firmwareversion":"5.01.23.24","chipset":"BCM972126OTT_V20","deviceid":"OEUFIwMDEzNzIwAA"}}

Risks: Medium

Signed-off-by: rajapriya_radhakrishnan <rajapriya_radhakrishnan@comcast.com>

2024-02-07 11:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/rdkservices?pullRequest=4894) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/rdkservices?pullRequest=4894) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/rdkservices?pullRequest=4894) it.</sub>

2024-02-08 14:27 UTC, anand-ky requested changes

2024-02-08 14:27 UTC, anand-ky commented on DeviceIdentification/Implementation/Broadcom/Broadcom.cpp
> +    inline std::string extractSerialNumber() const
Serial Number is already provided by https://rdkcentral.github.io/rdkservices/#/api/DeviceInfoPlugin?id=serialnumber. Checking why we need to duplicate.

2024-02-08 14:27 UTC, anand-ky commented on DeviceIdentification/Implementation/Broadcom/Broadcom.cpp
> +    {
Firmware version is already provided by https://rdkcentral.github.io/rdkservices/#/api/DeviceInfoPlugin?id=firmwareversion. Checking why we need to duplicate

2024-02-20 15:38 UTC, anand-ky approved these changes

2024-02-20 16:49 UTC, merged

2024-03-08 11:46 UTC, pradeeptakdas commented
Internal ticket for tracking https://ccp.sys.comcast.net/browse/RDKCOM-4587