RDKDEV-987 - Upstream PlayerInfo Resolution 2160P60 Changes
rdkcentral/rdkservices pull request #5010
Opened 2024-03-12 12:47 UTC by tkathi259

Reason for change: After setting resolution 2160P60, while fetching for PlayerInfo.resolution its returning 2160P60 instead of 2160P. As this is generic change, need to upstream the AMLS905X4-763_2160p-PlayerInfo_Resolution.patch file.

Risks: Low

Test Procedure:
TDK PlayerInfo test cases: SetAndGet_All_Supported_Resolutions

2024-03-12 12:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/rdkservices?pullRequest=5010) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/rdkservices?pullRequest=5010) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/rdkservices?pullRequest=5010) it.</sub>

2024-03-21 20:18 UTC, anand-ky requested changes

2024-03-21 20:18 UTC, anand-ky commented on PlayerInfo/DeviceSettings/PlatformImplementation.cpp
> -        {"2160p60", RESOLUTION_2160P60},
There is already entry for 2160p. Checking why are we changing this entry for 2160p60

2024-04-08 06:48 UTC, tkathi259 commented
Sprint branch is changed to "sprint/24Q2". So, i am closing this PR to create New one.

2024-04-08 06:48 UTC, closed without merging