SGMM393-181 : Upstream Return-exact-power-states Change
rdkcentral/rdkservices pull request #5201
Opened 2024-04-24 09:38 UTC by HarshiniRavichandran

This change is for "onSystemPowerStateChanged" event is not getting triggered for ON state

2024-04-24 12:36 UTC, pradeeptakdas commented
Internal ticket for tracking https://ccp.sys.comcast.net/browse/RDKCOM-4702

2024-04-24 16:39 UTC, sborushevsky approved these changes

2024-04-24 20:32 UTC, anand-ky commented
@apatel859 - Pls review

2024-04-29 18:11 UTC, apatel859 requested changes
first of all pull request should be between  rdkcentral:sprint/24Q2 and ur fork fro sprint/24Q2 
Also the jira descition and code changes are matching as code changes are related to fixing getPowerState where as jira text is regarding onState change event

2024-05-02 06:35 UTC, HarshiniRavichandran commented
Hi @apatel859, regarding the pull request between rdkcentral:sprint/24Q2 and my fork's sprint/24Q2 branch, I'll ensure that the Jira description accurately reflects the code changes.

2024-05-29 18:11 UTC, viveksinghnarwaria commented
Hi @HarshiniRavichandran ,
Not sure why are you trying to merge merge Pull Request from 24Q1 branch to 24Q2 branch. Please close this PR. I have created the correct PR https://github.com/rdkcentral/rdkservices/pull/5316.

2024-05-30 07:05 UTC, closed without merging