Sprint/2010
rdkcentral/rdkservices pull request #536
Opened 2020-12-07 09:22 UTC by ddevad

2020-12-07 19:03 UTC, apatel859 submitted a review, later dismissed

2020-12-08 21:34 UTC, anand-ky requested changes

2020-12-08 21:34 UTC, anand-ky commented on DisplaySettings/CMakeLists.txt
> +	install(FILES rfcdefaults/amlogic/displaysettings.ini
Pls include and package the displaySettings.ini file in gerrit in the specific amlogic oem repos.

2020-12-08 21:34 UTC, anand-ky commented on DisplaySettings/DisplaySettings.cpp
> +        std::shared_ptr<WPEFramework::JSONRPC::LinkType<WPEFramework::Core::JSON::IElement> > DisplaySettings::getThunderControllerClient(std::string callsign)
Appreciate if can move the getThunderControllerClient(), ActivatePlugin(), isPluginActivated() to helpers/utils.cpp. I see it's used in AVInput Plugin too and don't want to duplicate this code.

2020-12-09 17:32 UTC, closed without merging