Rdk 39655
rdkcentral/rdkservices pull request #5551
Opened 2024-07-22 19:40 UTC by AnanthaC

Notify the red recovery state changes

2024-07-22 19:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/rdkservices?pullRequest=5551) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/rdkservices?pullRequest=5551) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/rdkservices?pullRequest=5551) it.</sub>

2024-07-22 19:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/rdkservices?pullRequest=5551) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/rdkservices?pullRequest=5551) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/rdkservices?pullRequest=5551) it.</sub>

2024-07-22 19:43 UTC, sborushevsky approved these changes

2024-07-25 14:06 UTC, anand-ky requested changes
Pls fix the L1/L2 errors. Need to merge the dependent IARM changes first so that CI tests pass.

2024-09-06 11:14 UTC, closed without merging