DELIA-66647: Solicited Maintenance waits for onDeviceInitializationContextUpdate Event
rdkcentral/rdkservices pull request #5823
Opened 2024-10-29 08:48 UTC by gomathishankar37

2024-11-11 04:52 UTC, gomathishankar37 commented on MaintenanceManager/MaintenanceManager.cpp
> +                    if (!g_unsolicited_complete) {
Should `(UNSOLICITED_MAINTENANCE == g_maintenance_type)` check be added?

2024-11-11 04:53 UTC, gomathishankar37 commented on MaintenanceManager/MaintenanceManager.cpp
> +                if (!g_unsolicited_complete) {
Should `(UNSOLICITED_MAINTENANCE == g_maintenance_type)` check be added?

2024-11-20 12:45 UTC, tdeva14 requested changes
Can we do this?

```
bool activationStatus = false;
bool skipFirmwareCheck = false;
internetConnectStatus = false;

// Check if maintenance is suppressed and WhoAmI is not enabled
#if defined(SUPPRESS_MAINTENANCE) && !defined(ENABLE_WHOAMI)
    activationStatus = getActivatedStatus(skipFirmwareCheck);
    if (activationStatus) {
        internetConnectStatus = isDeviceOnline();
    }
#else // WhoAmI
    internetConnectStatus = isDeviceOnline();
#endif

#if defined(ENABLE_WHOAMI)
    bool whoAmIStatus = false;

    if (UNSOLICITED_MAINTENANCE == g_maintenance_type) {
        string activation_status = checkActivatedStatus(); // Only for unsolicited maintenance
        whoAmIStatus = knowWhoAmI(activation_status);
        LOGINFO(whoAmIStatus ? "knowWhoAmI() returned successfully" : "knowWhoAmI() returned false");

        if (!whoAmIStatus && activation_status != "activated") {
            LOGINFO("knowWhoAmI() returned false and Device is not already Activated");
            g_listen_to_deviceContextUpdate = true;
            LOGINFO("Waiting for onDeviceInitializationContextUpdate event");
            task_thread.wait(wailck); // Wait for the event
            // Continue with maintenance irrespective of network status
            internetConnectStatus = true;
        } else if (!internetConnectStatus && activation_status == "activated") {
            LOGINFO("Device is not connected to the Internet and Device is already Activated");
        }
    }
#endif

// Check internet connection status for all other cases
if (!internetConnectStatus) {
    m_statusMutex.lock();
    MaintenanceManager::_instance->onMaintenanceStatusChange(MAINTENANCE_ERROR);
    m_statusMutex.unlock();
    LOGINFO("Maintenance is exiting as device is not connected to internet.");
    
    if (UNSOLICITED_MAINTENANCE == g_maintenance_type && !g_unsolicited_complete) {
        g_unsolicited_complete = true;
        g_listen_to_nwevents = true;
    }
    return;
}

if (delayMaintenanceStarted) {
    m_statusMutex.lock();
    MaintenanceManager::_instance->onMaintenanceStatusChange(MAINTENANCE_STARTED);
    m_statusMutex.unlock();
}

LOGINFO("Reboot_Pending :%s", g_is_reboot_pending.c_str());
LOGINFO(UNSOLICITED_MAINTENANCE == g_maintenance_type ? "---------------UNSOLICITED_MAINTENANCE--------------" : "=============SOLICITED_MAINTENANCE===============");

#if defined(SUPPRESS_MAINTENANCE) && !defined(ENABLE_WHOAMI)
    if (activationStatus) {
        if (skipFirmwareCheck) {
            SET_STATUS(g_task_status, DIFD_SUCCESS);
            SET_STATUS(g_task_status, DIFD_COMPLETE);
            tasks.push_back(task_names_foreground[0].c_str());
            tasks.push_back(task_names_foreground[2].c_str());
        } else {
            tasks.push_back(task_names_foreground[0].c_str());
            tasks.push_back(task_names_foreground[1].c_str());
            tasks.push_back(task_names_foreground[2].c_str());
        }
    }
#else
    tasks.push_back(task_names_foreground[0].c_str());
    tasks.push_back(task_names_foreground[1].c_str());
    tasks.push_back(task_names_foreground[2].c_str());
#endif
```

2024-11-20 14:48 UTC, gomathishankar37 commented
> ``` 
> #if defined(ENABLE_WHOAMI)
>     bool whoAmIStatus = false;
> 
>     if (UNSOLICITED_MAINTENANCE == g_maintenance_type) {
>         string activation_status = checkActivatedStatus(); // Only for unsolicited maintenance
>         whoAmIStatus = knowWhoAmI(activation_status);
>         LOGINFO(whoAmIStatus ? "knowWhoAmI() returned successfully" : "knowWhoAmI() returned false");
> 
>         if (!whoAmIStatus && activation_status != "activated") {
>             LOGINFO("knowWhoAmI() returned false and Device is not already Activated");
>             g_listen_to_deviceContextUpdate = true;
>             LOGINFO("Waiting for onDeviceInitializationContextUpdate event");
>             task_thread.wait(wailck); // Wait for the event
>             // Continue with maintenance irrespective of network status
>             internetConnectStatus = true;
>         } else if (!internetConnectStatus && activation_status == "activated") {
>             LOGINFO("Device is not connected to the Internet and Device is already Activated");
>         }
>     }
> #endif
> ```
 @tdeva14 Could you please elaborate on `// Continue with maintenance irrespective of network status`? I want to ensure I address it accurately.  

Thanks

2025-01-06 04:41 UTC, closed without merging