SERXIONE-6196: DeviceIdentification activation fail
rdkcentral/rdkservices pull request #5910
Opened 2024-12-03 12:19 UTC by agampa263

Reason for change: DeviceIdentification plugin activation fail 
Test Procedure:Check DeviceIdentification plugin activation. 
Risks: Low
Signed-off-by:AkshayKumar_Gampa AkshayKumar_Gampa@comcast.com

2024-12-03 20:19 UTC, srikanth-vv requested changes

2024-12-03 20:19 UTC, srikanth-vv commented on DeviceIdentification/DeviceIdentification.cpp
> +#include <com/com.h>
Check if you need all these header files. I think ids.h is not needed. What about com.h, core.h?

2024-12-03 20:19 UTC, srikanth-vv commented on DeviceIdentification/DeviceIdentification.cpp
> +            auto _remoteDeviceInfoObject = _service->QueryInterfaceByCallsign<Exchange::IDeviceInfo>("DeviceInfo");
What is case of non USE_THUNDER_R4? Do you have to handle differently?

2024-12-13 14:23 UTC, anand-ky approved these changes

2024-12-13 14:23 UTC, anand-ky approved these changes

2024-12-13 14:27 UTC, merged