RDK-30533: Enable tv zoom settings
rdkcentral/rdkservices pull request #741
Opened 2021-01-25 10:40 UTC by mstrozyn

2021-01-25 11:56 UTC, mstrozyn commented
Verification build: https://gerrit.teamccp.com/#/c/475226/

2021-01-25 15:26 UTC, anand-ky requested changes

2021-01-25 15:26 UTC, anand-ky commented on DisplaySettings/DisplaySettings.cpp
> +                    if (!settingsJson.IElement::ToFile(settingsFile))
We should persist the values for all platforms and not just for Platco/LLama where these new zoom settings are added.

2021-01-26 16:42 UTC, anand-ky approved these changes
looks good.

2021-01-26 16:43 UTC, merged